name: Lint
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: "3.11"
        type: string
    secrets:
      personal_access_token:
        required: false
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install tools
        run: |
          pip install \
            ruff \
            mypy \
            types-shapely \
            types-geopandas \
            types-requests \
            pydantic \
            types-toml
      - name: Get changed Python files
        id: changed
        uses: tj-actions/changed-files@v47.0.6
        with:
          files: |
            **/*.py
      - name: Run Ruff
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed.outputs.all_changed_files }}"
          ruff check ${{ steps.changed.outputs.all_changed_files }} --config ./ruff.toml
      - name: Run Mypy
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed.outputs.all_changed_files }}"
          mypy ${{ steps.changed.outputs.all_changed_files }} --config-file ./mypy.ini
