name: lint-ci

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  lint:
    uses: cyclops-mrv/python-dev-standards/.github/workflows/lint.yml@main
    with:
      python-version: "3.11"  # Optional: override the default Python version
