name: Test Lint

on:
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        default: "3.11"
        type: string
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      python-version: ${{ github.event_name == 'workflow_dispatch' && inputs.python-version || '3.11' }}
